Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "mwrock/Windows2012R2"
  c.vm.hostname = "win2012R2"
  c.vm.communicator = "winrm"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.gui = true
    p.customize ["modifyvm", :id, "--usb", "off"]
  end
end
